FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Устанавливаем только production зависимости
RUN npm install --production

COPY . .

# Собираем Next.js
RUN npm run build

EXPOSE 3000

# Запуск оптимизированного продакшен-билда
CMD ["npm", "start"]
