# Базовый образ Node.js
FROM node:20-alpine

# Рабочая директория
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект
COPY . .

# Порт приложения
EXPOSE 3000

# Команда запуска dev-сервера
CMD ["npm", "run", "dev"]
